version: '3.8'

services:
  admin-dashboard:
    image: imranwebstudio/great2d-admin-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: great2d-admin-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
